'use client'

import Link from 'next/link'
import { ArrowLeft, CheckCircle2, UploadCloud } from 'lucide-react'
import { useEffect, useRef, useState } from 'react'

type Capture = { id:string; name:string; slug:string; capture_enabled:boolean; capture_delay_ms:number; capture_html:string; capture_css:string; capture_js:string }

export default function CapturePage({ params }: { params: Promise<{ id:string }> }) {
  const [funnelId,setFunnelId]=useState(''); const [capture,setCapture]=useState<Capture|null>(null); const [enabled,setEnabled]=useState(false); const [delay,setDelay]=useState(5); const [message,setMessage]=useState(''); const [busy,setBusy]=useState(false); const input=useRef<HTMLInputElement>(null)
  useEffect(()=>{params.then(p=>setFunnelId(p.id))},[params])
  useEffect(()=>{if(!funnelId)return;(async()=>{const r=await fetch(`/api/funnels/capture-page?funnelId=${encodeURIComponent(funnelId)}`);const j=await r.json();if(!r.ok){setMessage(j.error||'Chargement impossible.');return}setCapture(j.capture);setEnabled(j.capture.capture_enabled);setDelay(Math.round(j.capture.capture_delay_ms/1000))})()},[funnelId])
  async function save(file?:File){if(!funnelId)return;setBusy(true);setMessage('');try{const body=new FormData();body.append('funnelId',funnelId);body.append('enabled',String(enabled));body.append('delayMs',String(Math.min(30,Math.max(0,Number(delay)||0))*1000));if(file)body.append('file',file);const r=await fetch('/api/funnels/capture-page',{method:'POST',body});const j=await r.json();if(!r.ok)throw new Error(j.error||'Enregistrement impossible.');setCapture(j.capture);setMessage(file?'Page de capture importée et enregistrée.':'Paramètres enregistrés.')}catch(e){setMessage(e instanceof Error?e.message:'Enregistrement impossible.')}finally{setBusy(false)}}
  const preview=capture?.capture_html?`<!doctype html><html><head><meta name="viewport" content="width=device-width,initial-scale=1"><style>${capture.capture_css||''}</style></head><body>${capture.capture_html}<script>${capture.capture_js||''}<\\/script></body></html>`:''
  return <div className="page"><Link href={`/funnels/${funnelId}`} className="back"><ArrowLeft size={15}/>Tunnel</Link><div className="head"><div><small>PAGE DE CAPTURE</small><h1>{capture?.name||'Capture'}</h1><p>Formulaire affiché avant l’accès au contenu du tunnel.</p></div><button className="primary" onClick={()=>void save()} disabled={busy||!capture}><CheckCircle2 size={16}/>{busy?'Enregistrement…':'Enregistrer'}</button></div>{message&&<div className="notice">{message}</div>}<div className="panel"><div className="section-head"><div><h3>Configuration</h3><span className="muted">Importez votre propre design HTML.</span></div></div><div className="form-grid"><label className="field"><span>Afficher la capture</span><select value={enabled?'on':'off'} onChange={e=>setEnabled(e.target.value==='on')}><option value="on">Oui</option><option value="off">Non</option></select></label><label className="field"><span>Délai avant affichage (secondes)</span><input type="number" min="0" max="30" value={delay} onChange={e=>setDelay(Number(e.target.value))}/></label></div><div className="capture-import"><label className="outline upload-label import-button"><UploadCloud size={16}/>Importer le fichier HTML de capture<input ref={input} type="file" accept=".html,.htm,text/html" hidden onChange={e=>{const f=e.target.files?.[0];if(f)void save(f);e.currentTarget.value='' }}/></label><span className="muted">Le formulaire HTML sera relié automatiquement aux Contacts de CONIK.IO.</span></div></div>{capture?.capture_html&&<div className="panel"><div className="section-head"><h3>Aperçu</h3><span className="muted">Votre design importé</span></div><iframe title="Aperçu page de capture" sandbox="allow-scripts allow-forms" srcDoc={preview} style={{width:'100%',height:500,border:'1px solid #e5e7eb',borderRadius:12,background:'#fff'}}/></div>}</div>
}
