'use client'

import Link from 'next/link'
import { ArrowLeft, Copy, Radio, Trash2, Users } from 'lucide-react'
import { useEffect, useState } from 'react'
import { AppShell } from '@/components/app-shell'
import LiveRoom from '@/components/live/live-room'

type Participant={id:string;contact_id:string;email:string;status:string;invited_at:string}
type Live={id:string;title:string;description:string|null;slug:string;scheduled_at:string;timezone:string;status:string;stream_provider:string|null;stream_id:string|null}

export default function LiveDetail({params}:{params:Promise<{id:string}>}){
  const[live,setLive]=useState<Live|null>(null),[participants,setParticipants]=useState<Participant[]>([]),[contacts,setContacts]=useState<any[]>([]),[selected,setSelected]=useState(''),[error,setError]=useState(''),[notice,setNotice]=useState(''),[studio,setStudio]=useState(false)
  async function load(id:string){const [l,p,c]=await Promise.all([fetch('/api/lives').then(r=>r.json()),fetch(`/api/lives/${id}/participants`).then(r=>r.json()),fetch('/api/contacts').then(r=>r.json())]);setLive((l.lives||[]).find((x:Live)=>x.id===id)||null);setParticipants(p.participants||[]);setContacts(c.contacts||[])}
  useEffect(()=>{params.then(({id})=>load(id).catch(()=>setError('Impossible de charger cet événement')))},[params])
  async function add(){if(!live||!selected)return;setError('');const r=await fetch(`/api/lives/${live.id}/participants`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({contact_ids:[selected]})});const j=await r.json().catch(()=>({}));if(!r.ok)setError(j.error||'Impossible d’ajouter le contact');else{setSelected('');setNotice('Contact autorisé.');await load(live.id)}}
  async function remove(contactId:string){if(!live)return;const r=await fetch(`/api/lives/${live.id}/participants`,{method:'DELETE',headers:{'Content-Type':'application/json'},body:JSON.stringify({contact_id:contactId})});const j=await r.json().catch(()=>({}));if(!r.ok)setError(j.error||'Impossible de retirer le contact');else{setNotice('Contact retiré.');await load(live.id)}}
  function copy(){if(!live)return;navigator.clipboard?.writeText(`${window.location.origin}/live/${live.slug}`);setNotice('Lien copié.')}
  async function startStudio(){if(!live)return;setError('');const r=await fetch(`/api/lives/${live.id}/token`,{method:'POST'});const j=await r.json().catch(()=>({}));if(!r.ok){setError(j.error||'Impossible de démarrer le studio');return}setLive(v=>v?{...v,stream_provider:'livekit',stream_id:j.room}:v);setStudio(true);setNotice('Studio prêt. Autorisez caméra et micro si le navigateur le demande.')}
  const allowed=new Set(participants.map(p=>p.contact_id))
  return <AppShell active="Live Events"><div className="page"><Link href="/lives" className="back"><ArrowLeft size={15}/>Live Events</Link>{error&&<div className="error">{error}</div>}{notice&&<div className="notice">{notice}</div>}{!live?<div className="emptybox big">Chargement…</div>:<><div className="head"><div><small>LIVE PRIVÉ</small><h1>{live.title}</h1><p>{live.description||'Aucune description.'}</p></div><div style={{display:'flex',gap:8,flexWrap:'wrap'}}><button className="primary" onClick={startStudio}><Radio size={15}/>{studio?'Studio ouvert':'Démarrer le studio'}</button><button className="outline" onClick={copy}><Copy size={15}/>Copier le lien</button></div></div>{studio&&<section className="panel" style={{marginBottom:20}}><h3 style={{marginBottom:14}}>Studio du Live</h3><LiveRoom tokenUrl={`/api/lives/${live.id}/token`} tokenBody={{}} host/></section>}<div className="choice" style={{marginTop:20}}><b>Lien privé</b><div className="muted" style={{marginTop:6,wordBreak:'break-all'}}>{window.location.origin}/live/{live.slug}</div><p style={{fontSize:13}}>L’accès reste protégé côté serveur par la liste des contacts autorisés.</p></div><section className="panel" style={{marginTop:20}}><h3 style={{display:'flex',alignItems:'center',gap:8}}><Users size={18}/>Contacts autorisés ({participants.length})</h3><div style={{display:'flex',gap:8,marginTop:14,flexWrap:'wrap'}}><select className="form-input" value={selected} onChange={e=>setSelected(e.target.value)}><option value="">Ajouter un contact…</option>{contacts.filter(c=>c.email&&!allowed.has(c.id)).map(c=><option key={c.id} value={c.id}>{[c.first_name,c.last_name].filter(Boolean).join(' ')||c.email} — {c.email}</option>)}</select><button className="primary" onClick={add} disabled={!selected}>Autoriser</button></div><div className="table-wrap" style={{marginTop:16}}><table><thead><tr><th>E-mail</th><th>Statut</th><th>Ajouté le</th><th></th></tr></thead><tbody>{participants.map(p=><tr key={p.id}><td>{p.email}</td><td>{p.status}</td><td>{p.invited_at?new Date(p.invited_at).toLocaleString('fr-FR'):'—'}</td><td><button className="outline" onClick={()=>remove(p.contact_id)} aria-label="Retirer"><Trash2 size={15}/></button></td></tr>)}{participants.length===0&&<tr><td colSpan={4}>Aucun contact autorisé.</td></tr>}</tbody></table></div></section></>}</div></AppShell>
}
