'use client'

import Link from 'next/link'
import { ArrowLeft, Plus, Trash2, Save, Users, X } from 'lucide-react'
import { useEffect, useState } from 'react'

type Rule={field:string;operator:string;value:string}
type Segment={id:string;name:string;description:string|null;rules:Rule[];match_mode:'all'|'any';created_at:string;updated_at:string}
const fields=[['status','Status'],['consent_status','Consent'],['source','Source'],['tag','Tag']]
const operators=[['equals','equals'],['contains','contains'],['not_equals','does not equal']]

export default function Segments(){
 const[segments,setSegments]=useState<Segment[]>([]),[selected,setSelected]=useState<Segment|null>(null),[error,setError]=useState(''),[notice,setNotice]=useState(''),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[counts,setCounts]=useState<Record<string,number>>({})
 async function load(){setLoading(true);const r=await fetch('/api/segments');const j=await r.json().catch(()=>({}));if(!r.ok)setError(j.error||'Unable to load segments');else setSegments(j.segments||[]);setLoading(false)}
 useEffect(()=>{load()},[])
 function newSegment(){setError('');setNotice('');setSelected({id:'',name:'',description:'',rules:[{field:'status',operator:'equals',value:'active'}],match_mode:'all',created_at:'',updated_at:''})}
 function updateRule(i:number,key:keyof Rule,value:string){if(!selected)return;const rules=[...selected.rules];rules[i]={...rules[i],[key]:value};setSelected({...selected,rules})}
 function addRule(){if(selected)setSelected({...selected,rules:[...selected.rules,{field:'status',operator:'equals',value:''}]})}
 function removeRule(i:number){if(selected)setSelected({...selected,rules:selected.rules.filter((_,n)=>n!==i)})}
 async function save(){if(!selected||!selected.name.trim())return setError('Segment name is required.');if(selected.rules.some(r=>!r.value.trim()))return setError('Complete every rule before saving.');setSaving(true);setError('');const method=selected.id?'PATCH':'POST';const body={...selected,name:selected.name.trim(),rules:selected.rules.map(r=>({field:r.field,operator:r.operator,value:r.value.trim()}))};const r=await fetch('/api/segments',{method,headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const j=await r.json().catch(()=>({}));if(!r.ok)setError(j.error||'Unable to save segment');else{setNotice(selected.id?'Segment updated.':'Segment created.');setSelected(j.segment);await load()}setSaving(false)}
 async function remove(id:string){if(!confirm('Delete this segment?'))return;setError('');const r=await fetch('/api/segments',{method:'DELETE',headers:{'Content-Type':'application/json'},body:JSON.stringify({id})});const j=await r.json().catch(()=>({}));if(!r.ok)setError(j.error||'Unable to delete segment');else{if(selected?.id===id)setSelected(null);await load()}}
 return <div className="page"><Link href="/dashboard" className="back"><ArrowLeft size={15}/>Dashboard</Link><small>CRM</small><div style={{display:'flex',justifyContent:'space-between',alignItems:'center',gap:16,flexWrap:'wrap'}}><div><h1>Segments</h1><p>Create dynamic groups of contacts for targeted campaigns and automations.</p></div><button className="primary" onClick={newSegment}><Plus size={16}/> New segment</button></div>{error&&<div className="error" style={{marginTop:16}}>{error}</div>}{notice&&<div className="notice" style={{marginTop:16}}>{notice}</div>}
 <div style={{display:'grid',gridTemplateColumns:'minmax(260px,1fr) minmax(320px,2fr)',gap:18,marginTop:24}}>
  <div className="choice"><h2>Your segments</h2>{loading?<p className="muted">Loading…</p>:segments.length===0?<div className="emptybox"><Users size={24}/><b>No segments yet</b><p>Create your first dynamic audience.</p></div>:segments.map(s=><div key={s.id} style={{display:'flex',justifyContent:'space-between',alignItems:'center',gap:8,padding:'12px 0',borderBottom:'1px solid var(--border)'}}><button className="outline" style={{flex:1,textAlign:'left'}} onClick={()=>{setSelected(s);setNotice('');setError('')}}><b>{s.name}</b><br/><span className="muted">{s.rules.length} rule{s.rules.length===1?'':'s'} · {s.match_mode==='all'?'ALL':'ANY'}</span></button><button className="outline" onClick={()=>remove(s.id)} aria-label="Delete segment"><Trash2 size={15}/></button></div>)}</div>
  <div className="choice"><div style={{display:'flex',justifyContent:'space-between',alignItems:'center'}}><h2>{selected?'Segment builder':'Select a segment'}</h2>{selected&&<button className="outline" onClick={()=>setSelected(null)}><X size={15}/></button>}</div>{selected?<><input className="form-input" value={selected.name} onChange={e=>setSelected({...selected,name:e.target.value})} placeholder="Segment name"/><textarea className="form-input" value={selected.description||''} onChange={e=>setSelected({...selected,description:e.target.value})} placeholder="Description (optional)" style={{marginTop:10,minHeight:70}}/><div style={{marginTop:16}}><label>Match <select className="form-input" value={selected.match_mode} onChange={e=>setSelected({...selected,match_mode:e.target.value as 'all'|'any'})}><option value="all">ALL rules (AND)</option><option value="any">ANY rule (OR)</option></select></label></div>{selected.rules.map((r,i)=><div key={i} style={{display:'grid',gridTemplateColumns:'1fr 1fr 1.3fr auto',gap:8,marginTop:10,alignItems:'center'}}><select className="form-input" value={r.field} onChange={e=>updateRule(i,'field',e.target.value)}>{fields.map(x=><option key={x[0]} value={x[0]}>{x[1]}</option>)}</select><select className="form-input" value={r.operator} onChange={e=>updateRule(i,'operator',e.target.value)}>{operators.map(x=><option key={x[0]} value={x[0]}>{x[1]}</option>)}</select><input className="form-input" value={r.value} onChange={e=>updateRule(i,'value',e.target.value)} placeholder="Value"/><button className="outline" onClick={()=>removeRule(i)} disabled={selected.rules.length===1} aria-label="Remove rule"><X size={14}/></button></div>)}<button className="outline" style={{marginTop:12}} onClick={addRule}><Plus size={15}/> Add rule</button><div style={{display:'flex',gap:8,marginTop:18}}><button className="primary" onClick={save} disabled={saving}><Save size={15}/>{saving?'Saving…':'Save segment'}</button></div></>:<div className="emptybox big"><Users size={30}/><b>Build a targeted audience</b><p>Choose a segment on the left or create a new one.</p></div>}</div>
 </div></div>
}
