'use client'

import Link from 'next/link'
import { ArrowLeft, Plus, Trash2, Save, Users, X, RefreshCw } from 'lucide-react'
import { useEffect, useState } from 'react'

type Rule={field:string;operator:string;value:string}
type Segment={id:string;name:string;description:string|null;rules:Rule[];match_mode:'all'|'any';created_at:string;updated_at:string}
const fields=[['status','Statut'],['consent_status','Consentement'],['source','Source'],['tag','Étiquette']]
const operators=[['equals','est égal à'],['contains','contient'],['not_equals','n’est pas égal à']]

export default function Segments(){
 const[segments,setSegments]=useState<Segment[]>([]),[selected,setSelected]=useState<Segment|null>(null),[error,setError]=useState(''),[notice,setNotice]=useState(''),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[counts,setCounts]=useState<Record<string,number>>({}),[countLoading,setCountLoading]=useState<Record<string,boolean>>({})
 async function load(){setLoading(true);setError('');const r=await fetch('/api/segments');const j=await r.json().catch(()=>({}));if(!r.ok)setError(j.error||'Impossible de charger les segments');else{setSegments(j.segments||[]);await Promise.all((j.segments||[]).map((s:Segment)=>loadCount(s.id)))}setLoading(false)}
 async function loadCount(id:string){setCountLoading(x=>({...x,[id]:true}));const r=await fetch(`/api/segments/${id}/count`);const j=await r.json().catch(()=>({}));if(r.ok)setCounts(x=>({...x,[id]:Number(j.count)||0}));setCountLoading(x=>({...x,[id]:false}))}
 useEffect(()=>{load()},[])
 function newSegment(){setError('');setNotice('');setSelected({id:'',name:'',description:'',rules:[{field:'status',operator:'equals',value:'lead'}],match_mode:'all',created_at:'',updated_at:''})}
 function updateRule(i:number,key:keyof Rule,value:string){if(!selected)return;const rules=[...selected.rules];rules[i]={...rules[i],[key]:value};setSelected({...selected,rules})}
 function addRule(){if(selected)setSelected({...selected,rules:[...selected.rules,{field:'status',operator:'equals',value:''}]})}
 function removeRule(i:number){if(selected)setSelected({...selected,rules:selected.rules.filter((_,n)=>n!==i)})}
 async function save(){if(!selected||!selected.name.trim())return setError('Le nom du segment est obligatoire.');if(selected.rules.some(r=>!r.value.trim()))return setError('Complétez toutes les règles avant d’enregistrer.');setSaving(true);setError('');const method=selected.id?'PATCH':'POST';const body={...selected,name:selected.name.trim(),rules:selected.rules.map(r=>({field:r.field,operator:r.operator,value:r.value.trim()}))};const r=await fetch('/api/segments',{method,headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const j=await r.json().catch(()=>({}));if(!r.ok)setError(j.error||'Impossible d’enregistrer le segment');else{setNotice(selected.id?'Segment mis à jour.':'Segment créé.');setSelected(j.segment);await load()}setSaving(false)}
 async function remove(id:string){if(!confirm('Supprimer ce segment ?'))return;setError('');const r=await fetch('/api/segments',{method:'DELETE',headers:{'Content-Type':'application/json'},body:JSON.stringify({id})});const j=await r.json().catch(()=>({}));if(!r.ok)setError(j.error||'Impossible de supprimer le segment');else{if(selected?.id===id)setSelected(null);await load()}}
 return <div className="page"><Link href="/dashboard" className="back"><ArrowLeft size={15}/>Tableau de bord</Link><small>CRM</small><div style={{display:'flex',justifyContent:'space-between',alignItems:'center',gap:16,flexWrap:'wrap'}}><div><h1>Segments</h1><p>Créez des groupes dynamiques de contacts pour vos campagnes et automatisations ciblées.</p></div><button className="primary" onClick={newSegment}><Plus size={16}/> Nouveau segment</button></div>{error&&<div className="error" style={{marginTop:16}}>{error}</div>}{notice&&<div className="notice" style={{marginTop:16}}>{notice}</div>}
 <div style={{display:'grid',gridTemplateColumns:'minmax(260px,1fr) minmax(320px,2fr)',gap:18,marginTop:24}}>
  <div className="choice"><div style={{display:'flex',justifyContent:'space-between',alignItems:'center'}}><h2>Vos segments</h2><button className="outline" onClick={()=>load()} aria-label="Actualiser les segments"><RefreshCw size={15}/></button></div>{loading?<p className="muted">Chargement…</p>:segments.length===0?<div className="emptybox"><Users size={24}/><b>Aucun segment pour le moment</b><p>Créez votre première audience dynamique.</p></div>:segments.map(s=><div key={s.id} style={{display:'flex',justifyContent:'space-between',alignItems:'center',gap:8,padding:'12px 0',borderBottom:'1px solid var(--border)'}}><button className="outline" style={{flex:1,textAlign:'left'}} onClick={()=>{setSelected(s);setNotice('');setError('')}}><b>{s.name}</b><br/><span className="muted">{countLoading[s.id]?'Comptage…':`${counts[s.id]??0} contact${counts[s.id]===1?'':'s'}`} · {s.rules.length} règle{s.rules.length===1?'':'s'} · {s.match_mode==='all'?'TOUTES':'AU MOINS UNE'}</span></button><button className="outline" onClick={()=>remove(s.id)} aria-label="Supprimer le segment"><Trash2 size={15}/></button></div>)}</div>
  <div className="choice"><div style={{display:'flex',justifyContent:'space-between',alignItems:'center'}}><h2>{selected?'Générateur de segment':'Sélectionnez un segment'}</h2>{selected&&<button className="outline" onClick={()=>setSelected(null)}><X size={15}/></button>}</div>{selected?<><input className="form-input" value={selected.name} onChange={e=>setSelected({...selected,name:e.target.value})} placeholder="Nom du segment"/><textarea className="form-input" value={selected.description||''} onChange={e=>setSelected({...selected,description:e.target.value})} placeholder="Description (facultative)" style={{marginTop:10,minHeight:70}}/><div style={{marginTop:16}}><label>Correspondance <select className="form-input" value={selected.match_mode} onChange={e=>setSelected({...selected,match_mode:e.target.value as 'all'|'any'})}><option value="all">TOUTES les règles (ET)</option><option value="any">AU MOINS UNE règle (OU)</option></select></label></div>{selected.rules.map((r,i)=><div key={i} style={{display:'grid',gridTemplateColumns:'1fr 1fr 1.3fr auto',gap:8,marginTop:10,alignItems:'center'}}><select className="form-input" value={r.field} onChange={e=>updateRule(i,'field',e.target.value)}>{fields.map(x=><option key={x[0]} value={x[0]}>{x[1]}</option>)}</select><select className="form-input" value={r.operator} onChange={e=>updateRule(i,'operator',e.target.value)}>{operators.map(x=><option key={x[0]} value={x[0]}>{x[1]}</option>)}</select><input className="form-input" value={r.value} onChange={e=>updateRule(i,'value',e.target.value)} placeholder="Valeur"/><button className="outline" onClick={()=>removeRule(i)} disabled={selected.rules.length===1} aria-label="Supprimer la règle"><X size={14}/></button></div>)}<button className="outline" style={{marginTop:12}} onClick={addRule}><Plus size={15}/> Ajouter une règle</button><div style={{display:'flex',gap:8,marginTop:18,alignItems:'center'}}><button className="primary" onClick={save} disabled={saving}><Save size={15}/>{saving?'Enregistrement…':'Enregistrer le segment'}</button>{selected.id&&<span className="muted">{countLoading[selected.id]?'Calcul de l’audience…':`${counts[selected.id]??0} contact${counts[selected.id]===1?'':'s'} correspondant${counts[selected.id]===1?'':'s'}`}</span>}</div></>:<div className="emptybox big"><Users size={30}/><b>Créez une audience ciblée</b><p>Choisissez un segment à gauche ou créez-en un nouveau.</p></div>}</div>
 </div></div>
}
