'use client'

import Link from 'next/link'
import { ArrowLeft, Check, Users } from 'lucide-react'
import { FormEvent, useEffect, useState } from 'react'
import { AppShell } from '@/components/app-shell'

type Contact={id:string;email:string|null;first_name:string|null;last_name:string|null}

export default function NewLive(){
  const[contacts,setContacts]=useState<Contact[]>([]),[selected,setSelected]=useState<string[]>([]),[saving,setSaving]=useState(false),[error,setError]=useState('')
  useEffect(()=>{fetch('/api/contacts').then(r=>r.json()).then(j=>setContacts(j.contacts||[])).catch(()=>setError('Impossible de charger les contacts'))},[])
  function toggle(id:string){setSelected(v=>v.includes(id)?v.filter(x=>x!==id):[...v,id])}
  async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();setSaving(true);setError('');const f=new FormData(e.currentTarget);const scheduledAt=String(f.get('scheduled_at')||'');if(!scheduledAt){setError('Choisissez une date et une heure.');setSaving(false);return}const r=await fetch('/api/lives',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({title:f.get('title'),description:f.get('description'),scheduled_at:new Date(scheduledAt).toISOString(),timezone:f.get('timezone'),status:'scheduled'})});const j=await r.json().catch(()=>({}));if(!r.ok){setError(j.error||'Impossible de créer le Live');setSaving(false);return}if(selected.length){const p=await fetch(`/api/lives/${j.live.id}/participants`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({contact_ids:selected})});const pj=await p.json().catch(()=>({}));if(!p.ok){setError(pj.error||'Live créé, mais impossible d’ajouter les contacts.');setSaving(false);return}}window.location.assign(`/lives/${j.live.id}`)}
  return <AppShell active="Live Events"><div className="page"><Link href="/lives" className="back"><ArrowLeft size={15}/>Live Events</Link><small>NOUVEL ÉVÉNEMENT</small><h1>Créer un Live privé</h1><p>Le lien seul ne donne pas accès : seuls les e-mails sélectionnés dans votre CRM pourront entrer.</p>{error&&<div className="error" style={{marginTop:16}}>{error}</div>}<form onSubmit={submit} className="choice" style={{marginTop:24}}><div className="form-grid"><input className="form-input" name="title" required placeholder="Titre du Live"/><input className="form-input" name="scheduled_at" required type="datetime-local"/><input className="form-input" name="timezone" defaultValue="Africa/Lome" placeholder="Fuseau horaire"/><textarea className="form-input" name="description" placeholder="Description du Live" rows={4}/></div><div style={{marginTop:24}}><h2 style={{display:'flex',alignItems:'center',gap:8}}><Users size={19}/>Contacts autorisés</h2><p className="muted" style={{fontSize:13}}>Sélectionnez les contacts qui pourront s'inscrire avec leur adresse e-mail.</p><div style={{display:'grid',gap:8,maxHeight:320,overflowY:'auto',marginTop:12}}>{contacts.filter(c=>c.email).map(c=><label key={c.id} className="outline" style={{display:'flex',alignItems:'center',gap:10,cursor:'pointer'}}><input type="checkbox" checked={selected.includes(c.id)} onChange={()=>toggle(c.id)}/><span><b>{[c.first_name,c.last_name].filter(Boolean).join(' ')||'Contact'}</b><small style={{display:'block'}}>{c.email}</small></span>{selected.includes(c.id)&&<Check size={16}/>}</label>)}{contacts.filter(c=>c.email).length===0&&<div className="emptybox">Aucun contact avec e-mail. Ajoutez d'abord des contacts dans le CRM.</div>}</div></div><div style={{display:'flex',gap:8,marginTop:24}}><button className="primary" disabled={saving}>{saving?'Création…':'Créer le Live'}</button><Link className="outline" href="/lives">Annuler</Link></div></form></div></AppShell>
}
