'use client'

import Link from 'next/link'
import { ArrowLeft, Download, Search, Upload, UserPlus, Users, X } from 'lucide-react'
import { FormEvent, useEffect, useMemo, useRef, useState } from 'react'

type Contact = { id:string; email:string|null; phone:string|null; first_name:string|null; last_name:string|null; source:string|null; consent_marketing:boolean; status?:string|null; created_at:string }

export default function Contacts(){
  const[contacts,setContacts]=useState<Contact[]>([]),[query,setQuery]=useState(''),[error,setError]=useState(''),[notice,setNotice]=useState(''),[loading,setLoading]=useState(true),[show,setShow]=useState(false),[saving,setSaving]=useState(false),[importing,setImporting]=useState(false)
  const fileRef=useRef<HTMLInputElement>(null)
  async function load(){setLoading(true);setError('');const r=await fetch('/api/contacts');const j=await r.json().catch(()=>({}));if(!r.ok)setError(j.error||'Impossible de charger les contacts');else setContacts(j.contacts||[]);setLoading(false)}
  useEffect(()=>{load()},[])
  const filtered=useMemo(()=>{const q=query.trim().toLowerCase();if(!q)return contacts;return contacts.filter(c=>`${c.first_name||''} ${c.last_name||''} ${c.email||''} ${c.phone||''} ${c.source||''} ${c.status||''}`.toLowerCase().includes(q))},[contacts,query])
  async function add(e:FormEvent<HTMLFormElement>){e.preventDefault();setSaving(true);setError('');setNotice('');const form=e.currentTarget;const f=new FormData(form);const email=String(f.get('email')||'').trim();const phone=String(f.get('phone')||'').trim();if(!email&&!phone){setError('Saisissez une adresse e-mail ou un numéro de téléphone.');setSaving(false);return}const r=await fetch('/api/contacts',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({first_name:f.get('first_name'),last_name:f.get('last_name'),email,phone,source:'manual',consent_marketing:f.get('consent')==='on'})});const j=await r.json().catch(()=>({}));if(!r.ok)setError(j.error||'Impossible de créer le contact');else{setShow(false);form.reset();setNotice('Contact créé.');await load()}setSaving(false)}
  async function importCsv(e:React.ChangeEvent<HTMLInputElement>){const file=e.target.files?.[0];if(!file)return;setImporting(true);setError('');setNotice('');const fd=new FormData();fd.append('file',file);const r=await fetch('/api/contacts/csv',{method:'POST',body:fd});const j=await r.json().catch(()=>({}));if(!r.ok)setError(j.error||'Impossible d’importer le fichier CSV');else{setNotice(`${j.imported||0} contact${j.imported===1?'':'s'} importé${j.imported===1?'':'s'}. ${j.skipped||0} ignoré${j.skipped===1?'':'s'}.`);await load()}e.target.value='';setImporting(false)}
  function exportCsv(){window.location.assign('/api/contacts/csv')}
  return <div className="page">
    <Link href="/dashboard" className="back"><ArrowLeft size={15}/>Tableau de bord</Link><small>CRM</small>
    <div style={{display:'flex',justifyContent:'space-between',gap:16,alignItems:'center',flexWrap:'wrap'}}><div><h1>Contacts</h1><p>Tous les prospects captés par vos tunnels, dans une seule base de données.</p></div><div style={{display:'flex',gap:8,flexWrap:'wrap'}}><input ref={fileRef} type="file" accept=".csv,text/csv" hidden onChange={importCsv}/><button className="outline" disabled={importing} onClick={()=>fileRef.current?.click()}><Upload size={16}/>{importing?'Importation…':'Importer un CSV'}</button><button className="outline" disabled={!contacts.length} onClick={exportCsv}><Download size={16}/>Exporter en CSV</button><button className="primary" onClick={()=>{setError('');setNotice('');setShow(true)}}><UserPlus size={16}/> Ajouter un contact</button></div></div>
    {error&&<div className="error" style={{marginTop:16}}>{error}</div>}{notice&&<div className="notice" style={{marginTop:16}}>{notice}</div>}
    <div className="search" style={{marginTop:24,position:'relative'}}><Search size={16}/><input className="form-input" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Rechercher un nom, un e-mail, un téléphone, une source ou un statut…"/>{query&&<button type="button" className="outline" onClick={()=>setQuery('')} style={{padding:6,position:'absolute',right:6,top:5}} aria-label="Effacer la recherche"><X size={14}/></button>}</div>
    {show&&<div className="choice" style={{marginTop:18}}><div style={{display:'flex',justifyContent:'space-between',alignItems:'center',gap:12}}><h2>Nouveau contact</h2><button type="button" className="outline" onClick={()=>setShow(false)} aria-label="Fermer"><X size={16}/></button></div><form onSubmit={add}><div className="form-grid"><input className="form-input" name="first_name" placeholder="Prénom"/><input className="form-input" name="last_name" placeholder="Nom"/><input className="form-input" name="email" type="email" placeholder="E-mail"/><input className="form-input" name="phone" placeholder="Téléphone"/></div><p className="muted" style={{fontSize:13}}>L’e-mail ou le téléphone est obligatoire. Les contacts en doublon (e-mail/téléphone) sont refusés.</p><label><input name="consent" type="checkbox"/> Consentement marketing</label><div style={{display:'flex',gap:8,marginTop:14}}><button className="primary" disabled={saving}>{saving?'Enregistrement…':'Enregistrer le contact'}</button><button type="button" className="outline" onClick={()=>setShow(false)}>Annuler</button></div></form></div>}
    {loading?<div className="emptybox big">Chargement des contacts…</div>:filtered.length===0?<div className="emptybox big"><Users size={28}/><b>{query?'Aucun contact correspondant':'Aucun contact trouvé'}</b><p>{query?'Essayez un autre terme de recherche.':'Les prospects issus des formulaires de vos tunnels publiés apparaîtront ici.'}</p></div>:<><div className="muted" style={{marginTop:16,fontSize:13}}>{filtered.length} contact{filtered.length===1?'':'s'}{query?' correspondant à votre recherche':''}</div><div className="table-wrap" style={{marginTop:8}}><table><thead><tr><th>Nom</th><th>E-mail</th><th>Téléphone</th><th>Source</th><th>Statut</th><th>Consentement</th></tr></thead><tbody>{filtered.map(c=><tr key={c.id}><td><Link href={`/contacts/${c.id}`} style={{fontWeight:600}}>{[c.first_name,c.last_name].filter(Boolean).join(' ')||c.email||c.phone||'—'}</Link></td><td>{c.email||'—'}</td><td>{c.phone||'—'}</td><td>{c.source||'—'}</td><td>{c.status||'—'}</td><td>{c.consent_marketing?'Oui':'Non'}</td></tr>)}</tbody></table></div></>}
  </div>
}
